services:
  - type: worker
    name: telegram-youtube-bot
    env: python
    startCommand: python bot.py
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    envVars:
      - key: BOT_TOKEN
        sync: false
